name: OWASP Dependency-Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run OWASP Dependency-Check via Maven
        run: mvn org.owasp:dependency-check-maven:9.0.9:check -DfailOnError=false

      - name: Find and copy report to target folder
        run: |
          mkdir -p target
          # Recherche n'importe quel fichier de rapport HTML généré et le copie à l'emplacement attendu
          find . -name "dependency-check-report.html" -exec cp {} target/dependency-check-report.html \;
          # Afficher le contenu du dossier target pour vérification dans les logs
          ls -la target/

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html
