name: Trivy Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  trivy:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # (Optionnel) Si votre image est déjà sur Docker Hub, vous pouvez la scanner directement. 
      # Si vous voulez la builder avant, décommentez les lignes de build ci-dessous :
      - name: Build Docker image
        run: docker build -t moetezcherni044-hash/mon-projet-devsecops:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'moetezcherni044-hash/mon-projet-devsecops:latest'
          format: 'template'
          template: '@/contrib/html.tpl'
          output: 'trivy-report.html'

      - name: Upload Trivy report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.html
